porfolio-main/Portfolio-master/MainApp/Areas/Admin/Controllers/ChatBoxController.cs
using BuildingBlocks.Data;
using BuildingBlocks.Extensions;
using MainApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MainApp.Areas.Admin.Controllers;

public class ChatBoxController : ApiBaseController
{
    private readonly DatabaseContext _databaseContext;

    [ActivatorUtilitiesConstructor]
    public ChatBoxController(DatabaseContext databaseContext)
    {
        _databaseContext = databaseContext;
    }

    public async Task<IActionResult> Index(int? userId)
    {
        var chatBoxModel = new ChatBoxModel
        {
            Users = await _databaseContext.Users.Where(x => x.Id != User.GetId()).ToListAsync(),
            Rooms = await _databaseContext.Rooms.Where(x =>
                    x.CreatorId == User.GetId() ||
                    x.MemberId == User.GetId()
                )
                .Include(x => x.Messages)
                .ToListAsync()
        };
        if (userId != null)
        {
            var user = await _databaseContext.Users.FirstOrDefaultAsync(x => x.Id == userId);
            if (user != null)
                chatBoxModel.User = user;
            var currentUserId = User.GetId();
            var room = await _databaseContext.Rooms.Where(x =>
                    (x.CreatorId == currentUserId &&
                     x.MemberId == userId.Value) ||
                    (x.CreatorId == userId.Value &&
                     x.MemberId == currentUserId)
                )
                .FirstOrDefaultAsync();

            if (room != null)
            {
                var messages = await _databaseContext.Messages
                    .Where(x => x.RoomId == room.Id)
                    .Include(x => x.Creator)
                    .ToListAsync();
                chatBoxModel.Messages = messages;
            }
        }


        return View(chatBoxModel);
    }
}

porfolio-main/Portfolio-master/MainApp/Areas/Admin/Controllers/NewsController.cs
using System.Text;
using BuildingBlocks.Data;
using BuildingBlocks.Data.Entities;
using BuildingBlocks.Helpers;
using HtmlAgilityPack;
using MainApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MainApp.Areas.Admin.Controllers;

public class NewsController : ApiBaseController
{
    private readonly DatabaseContext _context;
    private readonly IWebHostEnvironment _webHostEnvironment;

    [ActivatorUtilitiesConstructor]
    public NewsController(DatabaseContext context, IWebHostEnvironment webHostEnvironment)
    {
        _context = context;
        _webHostEnvironment = webHostEnvironment;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var news = await _context.News.OrderByDescending(x => x.Id).ToListAsync();
        return View(news);
    }

    [HttpGet("Create")]
    public IActionResult Create()
    {
        return View();
    }

    [ValidateAntiForgeryToken]
    [HttpPost("Create")]
    public async Task<IActionResult> Create(NewsModel newsModel)
    {
        if (!string.IsNullOrEmpty(Request.Form["Crawl"].ToString()))
        {
            if (!Uri.IsWellFormedUriString(newsModel.Source, UriKind.Absolute))
                return View();

            var fullPath =
                new Uri("http://newspaper-demo.herokuapp.com/articles/show?url_to_clean=" + newsModel.Source);
            var htmlWeb = new HtmlWeb
            {
                AutoDetectEncoding = false,
                OverrideEncoding = Encoding.UTF8 //Set UTF8 để hiển thị tiếng Việt
            };

            var document = await htmlWeb.LoadFromWebAsync(fullPath.ToString());
            var title = document.DocumentNode.SelectSingleNode("/html/body/section/div/div/table/tbody/tr[1]/td[2]");
            var content = document.DocumentNode.SelectSingleNode("/html/body/section/div/div/table/tbody/tr[3]/td[2]");


            return View(new NewsModel
            {
                Content = content.InnerText.RemoveHtml(),
                Title = title.InnerText.RemoveHtml(),
                Source = newsModel.Source
            });
        }
        else
        {
            var images = await UploadedFile(newsModel.Images);
            var newEntity = new News
            {
                Title = newsModel.Title,
                Content = newsModel.Content,
                Images = images,
                Source = newsModel.Source
            };
            await _context.News.AddAsync(newEntity);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }

    [HttpGet("Delete")]
    public async Task<IActionResult> Delete(int id)
    {
        Console.WriteLine("sdfffffffffffffff");
        var news = await _context.News.FirstOrDefaultAsync(m => m.Id == id);
        if (news == null)
        {
            return RedirectToAction(nameof(Index));
        }

        _context.News.Remove(news);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private async Task<string> UploadedFile(List<IFormFile> files)
    {
        var fileNames = new List<string>();
        if (files == null || files.Count == 0)
            return string.Join(",", fileNames);
        foreach (var formFile in files)
        {
            if (formFile.Length > 0)
            {
                // full path to file in temp location
                var filePath = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                var fileExtension = Path.GetExtension(formFile.FileName);
                var filename = $"{Guid.NewGuid():N}{fileExtension}";
                var fileNameWithPath = Path.Combine(filePath, filename);
                await using var stream = new FileStream(fileNameWithPath, FileMode.Create);
                await formFile.CopyToAsync(stream);
                fileNames.Add(filename);
            }
        }

        return string.Join(",", fileNames);
    }
}

porfolio-main/Portfolio-master/MainApp/Areas/Admin/Controllers/PostsController.cs
using BuildingBlocks.Data;
using BuildingBlocks.Data.Entities;
using BuildingBlocks.Extensions;
using MainApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MainApp.Areas.Admin.Controllers;

public class PostsController : ApiBaseController
{
    private readonly DatabaseContext _databaseContext;

    [ActivatorUtilitiesConstructor]
    public PostsController(DatabaseContext databaseContext)
    {
        _databaseContext = databaseContext;
    }

    public async Task<IActionResult> Index()
    {
        var posts = await _databaseContext.Posts.OrderByDescending(x => x.Id).Include(p => p.User).ToListAsync();
        return View(posts);
    }


    [HttpGet("{postId:int}"), ActionName("Delete")]
    public async Task<IActionResult> Delete(int postId)
    {
        var post = await _databaseContext.Posts.FirstOrDefaultAsync(m => m.Id == postId);
        if (post == null)
        {
            return RedirectToAction(nameof(Index));
        }

        _databaseContext.Posts.Remove(post);
        await _databaseContext.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }
}

porfolio-main/Portfolio-master/MainApp/Areas/Admin/Controllers/UsersController.cs
using BuildingBlocks.Data;
using BuildingBlocks.Data.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MainApp.Areas.Admin.Controllers;

public class UsersController : ApiBaseController
{
    private readonly DatabaseContext _databaseContext;

    public UsersController(DatabaseContext databaseContext)
    {
        _databaseContext = databaseContext;
    }

    public async Task<IActionResult> Index()
    {
        return View(await _databaseContext.Users.Where(x => x.Role != UserRole.Admin).ToListAsync());
    }

    [HttpGet("{userId:int}")]
    public async Task<IActionResult> UpdateStatus(int userId)
    {
        var user = await _databaseContext.Users.FindAsync(userId);
        if (user == null)
            return RedirectToAction("Index");
        user.Status = user.Status == UserStatus.Disabled ? UserStatus.Enabled : UserStatus.Disabled;
        _databaseContext.Users.Update(user);
        await _databaseContext.SaveChangesAsync();
        return RedirectToAction("Index");
    }
}

porfolio-main/Portfolio-master/MainApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@(ViewData["Title"] ?? "Portfolio")</title>
    <link rel="stylesheet" href="~/style.css">
</head>
@if (TempData["AlertMessage"] != null)
{
    <div id="AlertBox" class="alert @TempData["AlertType"] hide" role="alert">
        @TempData["AlertMessage"]
    </div>
}
<body>
<nav class="navbar">
    <ul class="link-group">
        <li class="link">
            <a asp-action="Index" asp-controller="Home">Home</a>
        </li>
        <li class="link">
            <a asp-action="Details" asp-controller="UserSkills">Project</a>
        </li>
        <li class="link">
            <a asp-action="Index" asp-controller="UserSkills">About</a>
        </li>
        <li class="link">
            <a asp-action="Index" asp-controller="Posts">Forum</a>
        </li>
        <li class="link">
            <a asp-action="Index" asp-controller="News">News</a>
        </li>
        <li class="link">
            <a asp-action="Index" asp-controller="ChatBox">Chat box</a>
        </li>
        <li class="link">
            <a asp-action="Edit" asp-controller="Users">My Profiles</a>
        </li>
        <li class="link">
            <a asp-action="LogOut" asp-controller="Auth" asp-area="">Logout</a>
        </li>

    </ul>
    <form asp-controller="UserSkills" asp-action="IndexSearch" method="post" class="contact-form">
        <div class="input-group">
            <input style="margin: 0" name="username" type="text" class="form-control search-input" placeholder="Search for CV..." aria-label="Search" aria-describedby="search-addon">
        </div>
    </form>
</nav>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<div></div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@await RenderSectionAsync("Scripts", required: false)

@section Scripts {
    <script>
            $(function () {
                $('#AlertBox').removeClass('hide');
                $('#AlertBox').delay(2000).slideUp(500);
            });

        </script>
}

</body>
</html>

porfolio-main/Portfolio-master/MainApp/Views/Shared/_LayoutAdmin.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using BuildingBlocks.Extensions
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewData["Title"] - Admin</title>

    <!-- Custom fonts for this template-->
    <link href="/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.2/css/dataTables.bootstrap4.min.css">
    <!-- Custom styles for this template-->
    <link href="/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
        <li class="nav-item">
            <a class="nav-link" href="\Admin\Users">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Dashboard</span>
            </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Heading -->
        <div class="sidebar-heading">
            Interface
        </div>

        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
               aria-expanded="true" aria-controls="collapseTwo">
                <i class="fas fa-fw fa-cog"></i>
                <span>User Manager</span>
            </a>
            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <a class="collapse-item" asp-controller="Users" asp-action="Index" asp-area="Admin">User</a>
                </div>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
               aria-expanded="true" aria-controls="collapseUtilities">
                <i class="fas fa-fw fa-wrench"></i>
                <span>Post Manager</span>
            </a>
            <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                 data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header"> Manager : </h6>
                    <a class="collapse-item" asp-controller="Posts" asp-action="Index" asp-area="Admin">Post</a>
                    <a class="collapse-item" asp-controller="Comments" asp-action="Index" asp-area="Admin">Comment</a>
                </div>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="News" asp-action="Index" asp-area="Admin">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>News Manager</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="ChatBox" asp-action="Index" asp-area="Admin">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Chatbox</span>
            </a>
        </li>
        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>

    </ul>
    <!-- End of Sidebar -->
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            <!-- Topbar -->
            <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                <!-- Sidebar Toggle (Topbar) -->
                <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                    <i class="fa fa-bars"></i>
                </button>
                <!-- Topbar Navbar -->
                <ul class="navbar-nav ml-auto">

                    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                    <li class="nav-item dropdown no-arrow d-sm-none">
                        <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-search fa-fw"></i>
                        </a>
                        <!-- Dropdown - Messages -->
                        <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                             aria-labelledby="searchDropdown">
                            <form class="form-inline mr-auto w-100 navbar-search">
                                <div class="input-group">
                                    <input type="text" class="form-control bg-light border-0 small"
                                           placeholder="Search for..." aria-label="Search"
                                           aria-describedby="basic-addon2">
                                    <div class="input-group-append">
                                        <button class="btn btn-primary" type="button">
                                            <i class="fas fa-search fa-sm"></i>
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </li>

                    <li class="nav-item dropdown no-arrow">

                        <a class="nav-link dropdown-toggle" asp-controller="Users" asp-action="Index" asp-area="Admin" id="userDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="mr-2 d-none d-lg-inline text-gray-600 small">@TempData.Peek("Message")</span>
                            <img src="~/images/@(string.IsNullOrEmpty(User.GetAvatar()) ? "default-avatar.png" : User.GetAvatar())" class="img-profile rounded-circle" alt="">
                        </a>

                        <!-- Dropdown - User Information -->
                        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                             aria-labelledby="userDropdown">
                            <a class="dropdown-item" data-toggle="modal" data-target="#logoutModal">
                                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                Logout
                            </a>
                        </div>
                    </li>
                </ul>

            </nav>
            <!-- End of Topbar -->
            <!-- Begin Page Content -->
            <div class="container-fluid">

                <!-- Page Heading -->
                @RenderBody()

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->
        <!-- Footer -->
        <footer class="sticky-footer bg-white">
            <div class="container my-auto">
                <div class="copyright text-center my-auto">
                    <span>Copyright &copy; </span>
                </div>
            </div>
        </footer>
        <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->
<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a asp-action="Logout" asp-controller="Auth" asp-area="" class="btn btn-primary">Logout</a>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript-->
<script src="/vendor/jquery/jquery.min.js"></script>
<script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="/vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for all pages-->
<script src="/js/sb-admin-2.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("scripts", required: false)
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.11.2/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.2/js/dataTables.bootstrap4.min.js"></script>
<script>
        $(document).ready(function () {
            $('#example').DataTable();
        });
    </script>
</body>

</html>